cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://github.com/rianfernandesno
file:
  upload-dir: /Users/Rian/code/UploadDir
spring:
  application:
    name: rest-spring-application
  datasource:
    url: jdbc:mysql://localhost:3306/rest_spring_application?useTimezone=true&serverTimezone=UTC
    username: ${usernameDB}
    password: ${passwordDB}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
servlet:
  multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 200MB
    max-request-size: 215MB
logging:
    level:
      # root: WARN
      br.com.yui: DEBUG
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
